user/models.py
from application import db

from utilities.common import utc_now_ts as now

class User(db.Document):
    username = db.StringField(db_field="u", required=True, unique=True)
    password = db.StringField(db_field="p", required=True)
    email = db.EmailField(db_field="e", required=True, unique=True)
    first_name = db.StringField(db_field="fn", max_length=50)
    last_name = db.StringField(db_field="ln", max_length=50)
    created = db.IntField(db_field="c", default=now())
    bio = db.StringField(db_field="b", max_length=160)

    meta = {
        'indexes': ['username', 'email', '-created']
    }

user/forms.py
from flask_wtf import Form
from wtforms import validators, StringField, PasswordField
from wtforms.fields.html5 import EmailField
from wtforms.validators import ValidationError

from user.models import User

class RegisterForm(Form):
    first_name = StringField('First Name', [validators.DataRequired()])
    last_name = StringField('Last Name', [validators.DataRequired()])
    email = EmailField('Email address', [
        validators.DataRequired(),
        validators.Email()
        ]
    )
    username = StringField('Username', [
        validators.DataRequired(),
        validators.length(min=4, max=25)
        ])

    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Passwords must match'),
        validators.length(min=4, max=80)
        ])
    confirm = PasswordField('Repeat Password')

    def validate_username(form, field):
        if User.objects.filter(username=field.data).first():
            raise ValidationError("Username already exists")

    def validate_email(form, field):
        if User.objects.filter(email=field.data).first():
            raise ValidationError("Email is already in use")

class LoginForm(Form):
    username=StringField('Username',[
        validators.DataRequired(),
        validators.length(min=4, max=25)
    ])

    password=PasswordField('Password',[
        validators.DataRequired(),
        validators.length(min=4, max=80)
    ])

user/views.py
from flask import Blueprint, render_template, request, redirect, session, url_for
import bcrypt

from user.models import User
from user.forms import RegisterForm, LoginForm

user_app = Blueprint('user_app',__name__)

@user_app.route('/register', methods=('GET', 'POST'))
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)
        user = User(
            username = form.username.data,
            password = hashed_password,
            email = form.email.data,
            first_name = form.first_name.data,
            last_name = form.last_name.data
        )
        user.save()
        return "User registered"
    return render_template('user/register.html', form=form)

@user_app.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    error = None

    # Save the url, it will be redirect after the login
    if request.method == 'GET' and request.args.get('next'):
        session['next'] = request.args.get('next')

    if form.validate_on_submit():
        user = User.objects.filter(
            username = form.username.data
        ).first()

        if user:
            if bcrypt.hashpw(form.password.data, user.password) == user.password:
                session['username'] = form.username.data
                if 'next' in session:
                    next = session.get('next')
                    session.pop('next')
                    return redirect(next)
                else:
                    return 'User logged in '
        if not user:
            error = 'Incorrect credentials'

    return render_template('user/login.html', form=form, error=error)

@user_app.route('/logout', methods=('GET', 'POST'))
def logout():
    session.pop('username')
    redirect(url_for('user_app.login'))

utilities/__init__.py
import time

def utc_now_ts():
    return int(time.time())

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class="text-danger">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

  </head>
  <body>

    <div class="container">

    {% block content %}{% endblock %}

      <div class="col-md-offset-3 col-md-6">
        <hr />
        <footer>
          &copy; copyright 2017 flaskbook
        </footer>
      </div>

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.1.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">
                <img alt="flaskbook logo" width="82" height="20" src="{{ url_for('static', filename='assets/flaskbook-logo-sm.png') }}">
            </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if session.username %}
                <li>
                    <p class="navbar-text">Welcome, <a href="#" class="navbar-link">{{ session.username }}</a></p>
                </li>
                <li>
                    <a href="{{ url_for('user_app.logout') }}" class="navbar-link">Logout</a></p>
                </li>
                {% else %}
                <li>
                    <a href="{{ url_for('user_app.login') }}" class="navbar-link">Login</a></p>
                </li>
                <li>
                    <a href="{{ url_for('user_app.register') }}" class="navbar-link">Register</a></p>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/user/login.html
{% extends "base.html" %}

{% include "navbar.html" %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>User Login</h3>

    {% if error %}
    <div class="error text-danger">{{ error }}</div>
    {% endif %}

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('.login')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.username, class='form-control') }}
      {{ render_field(form.password, class='form-control') }}

      <button type="submit" class="btn btn-default">Login</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>Registration</h3>

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('user_app.register')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.first_name, class='form-control') }}
      {{ render_field(form.last_name, class='form-control') }}

      {{ render_field(form.username, class='form-control') }}
      {{ render_field(form.email, class='form-control') }}

      {{ render_field(form.password, class='form-control') }}
      {{ render_field(form.confirm, class='form-control') }}

      <button type="submit" class="btn btn-default">Register</button>

    </form>

  </div>

</div>
{% endblock %}